language: c
sudo: required
dist: trusty

services:
  - docker

before_script:
  - docker build -t centos7 -f contrib/Dockerfile .

script:
  - docker run -t -v `pwd`:/build centos7 ./pylint_test.py
  - docker run --privileged -t -v `pwd`:/build centos7 pytest --cov=lvfs --cov=plugins --cov=pkgversion --cov=infparser --cov=cabarchive --cov-fail-under=60
